### ISSUE TITLE
Races

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#10]
Racial stat bonuses are pretty clearly flawed and cause more problems than the flavor they add.

What do races give instead?

**Comment by plof27** [comment]
I think each race gets bonus effect. For example, warforged cannot get sick, and do not need to eat.

**Comment by alice-i-cecile** [comment]
I'd probably do two mostly-flavour features per race, plus one background feat that offers actual power.

**Comment by plof27** [comment]
I like that plan

**Comment by alice-i-cecile** [comment]
Race framework complete.
