### ISSUE TITLE
Cooldowns

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#17]
Is there a good place for cooldowns? Are they useful addition to mana-based power?

Certainly adds complexity to things that need to be tracked.

**Comment by alice-i-cecile** [comment]
Being able to use cool utility features without considering "but I could be doing other stuff with those resources!" feels really nice. You just need to decide whether this is the best time within that period you have to use it.

**Comment by plof27** [comment]
Agree there. That was our main hangup to moving everything to being mana abilities. Honestly I think we're fine with using cooldowns, with the suggestion that all cooldowns be on short rest. That way all everything is refreshing on short rest, except for HP. Easy to remember and track.

**Comment by alice-i-cecile** [comment]
Yeah, that seems sensible. I guess I worry that adding like divination abilities on a short rest basis may limit their power or make them too annoying?

**Comment by alice-i-cecile** [comment]
But OTOH, that means you can just keep short-resting forever unless you need HP. Which is super flavourful. Long rests are for when you need to recover your wounds.

**Comment by plof27** [comment]
Yeah. Honestly we're fine with limiting divination power. Incentivizing players to do more traditional investigation is good imo.

**Comment by alice-i-cecile** [comment]
Deal. I'm happy with this as a conclusion. If utility abilities are too annoying as a short-rest recharge then there's probably a larger issue.
