### ISSUE TITLE
Rename Charisma

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#18]
Avoiding namespace conflict is nice for not confusing new players.

**Comment by alice-i-cecile** [comment]
Charm?

**Comment by plof27** [comment]
i was thinking machismo but charm is good too yeah -p
Charm has a namespace conflict with motw, but they mean the same thing, and it's more likely to be getting new players from 5e, so I don't think it's a big deal.

**Comment by alice-i-cecile** [comment]
It shall be done.
