### ISSUE TITLE
Experience and levelling

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#19]
"ok i know i'm talking about motw a lot but i really like it. anyway the way they do xp is by asking a set of questions at the end of each session/arc. for every yes, the whole party gets 1xp. questions are like: "did we learn something new about the world?", "did we learn something new about one of our characters?", "did we save the day?", and some others i can't remember at present moment. anyway it's a nice way to reward good rp, and also do session recaps."

**Comment by plof27** [comment]
Many systems also have mechanics where you gain experience on failed rolls. That could be worth playing around with.

**Comment by plof27** [comment]
The four questions from MotW: 
- Did we conclude the current mystery?
- Did we save someone from certain death (or worse)?
- Did we learn something new and important about the world?
- Did we learn something new and important about one of the hunters?
If you get one or two "Yes" answers, mark one experience. If you get three or four, mark two.

**Comment by alice-i-cecile** [comment]
Bonus for being pushed to your limit?

**Comment by alice-i-cecile** [comment]
Experience points when you gain exhaustion due to overexerting.

**Comment by alice-i-cecile** [comment]
Experience points for gaining elemental essence crystals.

**Comment by alice-i-cecile** [comment]
Complete.
