### ISSUE TITLE
Crowd control chaining

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#21]
Really negates boss fights. Hard to balance single-target CC in group vs boss fight.

5e uses Legendary Resistance to get around this.

**Comment by plof27** [comment]
We've seen systems do it with good ol' negative feedback loops on repeatedly cc'ing the same target. Example: Darkest Dungeon gives enemies resistance to {CC Type} on the turn that they recover from {CC Type}. In this system could basically just be a buff to all saves for one turn, or some similar. (There are other methods too, but this was the first that came to mind)

**Comment by alice-i-cecile** [comment]
Mutiple turns per round for bosses does pretty okay at both this and multiattack. More elegant than having to make up multiattack features for every single serious enemy.

Would have to tweak movement speed rules to compensate.

**Comment by plof27** [comment]
We like the idea of boss monsters getting a turn for every 1-2 player turns or something. Just feels really gamey. "This is the final boss so they get the extra turns thing."

**Comment by alice-i-cecile** [comment]
Solved by extra turns for boss monsters.
