### ISSUE TITLE
Should we make separate rulebooks for new players vs players coming from 5e?

### ISSUE THREAD

**Issue by plof27** [alice-i-cecile/Fonts-of-Power#27]
Most 5e players I know would probably just prefer a diff from this and 5e, but new players would need more full explanation. I think drafting two versions is useful here.

**Comment by alice-i-cecile** [comment]
I'd create a cheatsheet for this but have one official rulebook with the rules from scratch.

**Comment by plof27** [comment]
sounds reasonable
