### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#44]
No need to put skill proficiencies here, or knowledges. Instead focus on the cool RP features.

**Comment by alice-i-cecile** [comment]
Choose both a Home and Away feature. Home gives you benefits while surrounded by allies or in familiar territory; Away lets you make new friends or explore more easily.

**Comment by alice-i-cecile** [comment]
5e backgrounds really struggle due to this, because they intend to be useful in strange lands. But as a tradeoff, there's no sense of home, either innate or accquired, supported.

**Comment by alice-i-cecile** [comment]
Choose a powerful feature ala feats.

**Comment by alice-i-cecile** [comment]
@plof27 uncertain about adding exploration features.

**Comment by plof27** [comment]
Part of my problem here is trying to distinguish home vs away. What about drifters who have been wandering their whole lives? There are ways to can define this for everyone, but it's fuzzy in a way I don't like, and it adds another thing to try and track. Trying to figure out whether your in a situation where {bonus} applies was always one of my least favorite parts about 5e. Also, I don't think a ton of power should be coming from background. I like the single feat better.

**Comment by alice-i-cecile** [comment]
Solved. One skill talent and one combat talent.
