### ISSUE TITLE
Change Treat and Affliction clearing

### ISSUE THREAD

**Issue by plof27** [alice-i-cecile/Fonts-of-Power#440]
1. Afflictons should tick down one of each type each turn
2. Treat should be changed
  a. Remove all stacks of one type of affliction at a scaling cost (more stacks = higher DC)
  b. Remove all stacks of one type of condition at a scaling cost (more stacks = higher DC)

**Comment by alice-i-cecile** [comment]
Complete! 10 + 2* stacks; removes half stacks of afflictions.
