### ISSUE TITLE
Radius counting

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#51]
Should formalize. 5 foot radius has been used to mean "this tile and all adjacent" to me. Every 5 feet past it extends by one tile (assuming hex grid).

**Comment by alice-i-cecile** [comment]
Likely moving directly to a tile system of measurement is better.

**Comment by alice-i-cecile** [comment]
Theatre of the mind seems really poorly suited to this system in general.

**Comment by plof27** [comment]
People will theatre of the mind anything, in my experience. And I still think those groups should have the option of at least _trying_. Also, it lets you more easily switch to square grid. Having to just know that each tile is 5 feet is annoying, but something I can definitely live with. Those calculations for sizes are fine. Most of the square grid folks I know just use a compass and guestimate.

**Comment by alice-i-cecile** [comment]
Not fixing; this is fine.
