### ISSUE TITLE
Add affix for attached to enable swapping ala Wild talent

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#554]

**Comment by plof27** [comment]
This should replace free hands and attached

This should specify that you gain the benefits and drawbacks of only the arms you most recently attacked with

**Comment by alice-i-cecile** [comment]
Clean up Wild, Awakened, Automaton and Ascendant in the process.

**Comment by alice-i-cecile** [comment]
Start of your turn, gain the benefits of the Swap minor action?
