### ISSUE TITLE
Fix formatting and class features for every class

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#568]
Double check name of attribute improvement, update normal text and headings, add proficiency bonus to class table.

**Comment by plof27** [comment]
- ensure that proficiency bonus is being used
- update text and headings to the new fonts
- add proficiency bonus to class table (with new numbers)
- check that none of the features (healing!) are using prof - 1
- make sure ASI's are listed as "attribute improvements"

**Comment by plof27** [comment]
- change "Proficiency Bonus Increase" to "Proficiency Bonus Improvement"

**Comment by plof27** [comment]
- Remove proficiency bonus column, add "Proficiency Bonus Improvement" to the table as a feature
- Add the proficiency bonus table to the section in the class description

**Comment by plof27** [comment]
- Swap to two column landscape layout
