### ISSUE TITLE
Weapon and armor proficiencies

### ISSUE THREAD

**Issue by alice-i-cecile** [alice-i-cecile/Fonts-of-Power#9]
Physique allowing you to use fancier custom armor and weapons seems really cool, and fixes the "everyone uses a rapier" problem.

Also encourages less martial classes to invest in physique.

Point buy system, separated by armor and weapons seems like the way to go. Shield points feel like they go with weapon points TBH.

**Comment by plof27** [comment]
It looks like there's one global physical attack modifier and one global magic attack modifier. This is fine, but how should proficiency work into that? I'd imagine classes are either proficient in one or the other. I guess you could let people choose weapons, but that feels messy, and the single global modifier would have to be axed.

**Comment by alice-i-cecile** [comment]
Completed.
